[build-system]
requires = ["maturin>=1.8.3"]
build-backend = "maturin"

[project]
name = "pyimgal"
version = "0.1.1.dev0"
description = "Python wrapper and bindings for imgal."
authors = [{ name = "Edward Evans", email = "elevans2@wisc.edu" }]
license = "Unlicense"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "maturin>=1.8.3",
]
keywords = ["image-processing", "algorithm", "rust"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
]
