[package]
name = "imgal_core"
version = "0.1.0"
authors = ["Edward Evans"]
edition = "2024"

[lib]
name = "imgal_core"
crate-type = ["rlib"]

[dependencies]
ndarray = { version = "0.16.0", features = ["rayon"] }
rayon = "1.10.0"
rustfft = "6.3"
